version: "3.9"

services:
  tests:
    build: .
    command: "dotnet test --logger:trx -r ${ENGI_TEST_RUNNER_OUTPUT_DIR:-/tmp}"
    volumes:
      # share the source code for live reloading
      - .:/code
      # bind mount /tmp from the host to share the output of test runner
      - type: bind
        source: ${ENGI_TEST_RUNNER_OUTPUT_DIR:-/tmp}
        target: ${ENGI_TEST_RUNNER_OUTPUT_DIR:-/tmp}
