version: "3.9"

services:
  tests:
    build: .
    command: dotnet test --logger:trx -r ${ENGI_TEST_RUNNER_OUTPUT_DIR}
    volumes:
      # share the source code for live reloading
      - .:/code
      # bind mount a directory to share the output of the test runner
      - type: bind
        source: ${ENGI_TEST_RUNNER_OUTPUT_DIR}
        target: ${ENGI_TEST_RUNNER_OUTPUT_DIR}
